name: "Set version"
description: ""

inputs:
  version:
    description: "Version"
    required: true
  githubToken:
    description: "Github token"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - run: pnpm run actions-set-version ${{ inputs.version }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
