import { ColorPaletteTransform, VarValueReplaceTransform } from "./ColorPaletteTransform";

export const COLOR_TRANSFORMS = [
  new ColorPaletteTransform("color-primary", "primary", "default"),
  new ColorPaletteTransform("color-primary", "primary", "text"),
  new ColorPaletteTransform("color-primary-contrast", "primary", "default-contrast"),

  new ColorPaletteTransform("color-secondary", "secondary", "default"),
  new ColorPaletteTransform("color-secondary", "secondary", "text"),
  new ColorPaletteTransform("color-secondary-contrast", "secondary", "default-contrast"),

  new ColorPaletteTransform("color-error", "error", "default"),
  new ColorPaletteTransform("color-error", "error", "text"),
  new ColorPaletteTransform("color-error-contrast", "error", "default-contrast"),

  new ColorPaletteTransform("color-primary-tint-lowest", "primary", "default", (c) => c.setA(0.04)),
  new ColorPaletteTransform("color-primary-tint-lowest", "primary", "default", (c) => c.setA(0.05)),
  new ColorPaletteTransform("color-primary-tint-low", "primary", "default", (c) => c.setA(0.1)),
  new ColorPaletteTransform("color-primary-tint", "primary", "default", (c) => c.setA(0.2)),
  new ColorPaletteTransform("color-primary-tint", "primary", "default", (c) => c.setA(0.25)),
  //new ColorPaletteTransform("color-primary-tint-higher", "primary", "default", (c) => c.setA(0.5)),
  new ColorPaletteTransform("color-primary-tint-highest", "primary", "default", (c) => c.setA(0.87)),

  new ColorPaletteTransform("color-secondary-tint-lowest", "secondary", "default", (c) => c.setA(0.04)),
  new ColorPaletteTransform("color-secondary-tint-lowest", "secondary", "default", (c) => c.setA(0.05)),
  new ColorPaletteTransform("color-secondary-tint-low", "secondary", "default", (c) => c.setA(0.1)),
  new ColorPaletteTransform("color-secondary-tint", "secondary", "default", (c) => c.setA(0.2)),
  new ColorPaletteTransform("color-secondary-tint", "secondary", "default", (c) => c.setA(0.25)),
  //new ColorPaletteTransform("color-secondary-tint-higher", "secondary", "default", (c) => c.setA(0.5)),
  new ColorPaletteTransform("color-secondary-tint-highest", "secondary", "default", (c) => c.setA(0.87)),

  new ColorPaletteTransform("color-error-tint-lowest", "error", "default", (c) => c.setA(0.04)),
  new ColorPaletteTransform("color-error-tint-lowest", "error", "default", (c) => c.setA(0.05)),
  new ColorPaletteTransform("color-error-tint-low", "error", "default", (c) => c.setA(0.1)),
  new ColorPaletteTransform("color-error-tint", "error", "default", (c) => c.setA(0.2)),
  new ColorPaletteTransform("color-error-tint", "error", "default", (c) => c.setA(0.25)),
  //new ColorPaletteTransform("color-error-tint-higher", "error", "default", (c) => c.setA(0.5)),
  new ColorPaletteTransform("color-error-tint-highest", "error", "default", (c) => c.setA(0.87)),

  new ColorPaletteTransform("color-overlay", "background", "disabled"),

  new ColorPaletteTransform("color-background-base", "background", "status-bar"),
  new ColorPaletteTransform("color-background-?", "background", "app-bar"),
  new ColorPaletteTransform("color-background-?", "background", "selected-button"),

  new ColorPaletteTransform("color-background-??", "background", "unselected-chip"),
  new ColorPaletteTransform("color-background-??", "background", "tooltip"), // unused

  new ColorPaletteTransform("color-background", "background", "background"),

  new ColorPaletteTransform("color-surface", "background", "card"),
  new ColorPaletteTransform("color-surface", "background", "dialog"),
  new ColorPaletteTransform("color-surface", "background", "raised-button"),
  new ColorPaletteTransform("color-surface", "background", "selected-disabled-button"),

  new ColorPaletteTransform("color-surface-tint-highest", "background", "card", (c) => c.setA(0.87)),

  new ColorPaletteTransform("color-background-base", "background", "disabled-button-toggle"),

  new ColorPaletteTransform("color-background-contrast", "foreground", "text"),
  new ColorPaletteTransform("color-background-contrast", "foreground", "icon"),
  new ColorPaletteTransform("color-background-contrast-low", "foreground", "secondary-text"),
  new ColorPaletteTransform("color-background-contrast-lower", "foreground", "hint-text"),

  new ColorPaletteTransform("color-overlay-base", "foreground", "base"),
  new ColorPaletteTransform("color-overlay-low", "foreground", "base", (c) => c.setA(0.1)),
  new ColorPaletteTransform("color-overlay-low", "foreground", "base", (c) => c.setA(0.12)),
  new ColorPaletteTransform("color-overlay-higher", "foreground", "base", (c) => c.setA(0.5)),
  new ColorPaletteTransform("color-overlay-higher", "foreground", "base", (c) => c.setA(0.54)),
  new ColorPaletteTransform("color-overlay-highest", "foreground", "base", (c) => c.setA(0.87)),

  new ColorPaletteTransform("color-overlay-low", "foreground", "divider"),
  new ColorPaletteTransform("color-overlay-higher", "foreground", "disabled"),
  new ColorPaletteTransform("color-overlay", "foreground", "disabled-button"),
  new ColorPaletteTransform("color-overlay-higher", "foreground", "disabled-text"),
  new ColorPaletteTransform("color-overlay-higher", "foreground", "disabled-text"),

  new ColorPaletteTransform("color-overlay-base", "foreground", "slider-min"),
  new ColorPaletteTransform("color-overlay", "foreground", "slider-off"),
  new ColorPaletteTransform("color-overlay", "foreground", "slider-off-active"),
  new ColorPaletteTransform("color-overlay-high", "background", "hover"),
  new ColorPaletteTransform("color-overlay-low", "background", "disabled-button"),
  new ColorPaletteTransform("color-overlay-low", "background", "focused-button"),
  new ColorPaletteTransform("color-overlay-low", "background", "disabled-list-option"),

  // REFS
  new ColorPaletteTransform("color-primary--ref--50", "primary", "50"),
  new ColorPaletteTransform("color-primary--ref--100", "primary", "100"),
  new ColorPaletteTransform("color-primary--ref--200", "primary", "200"),
  new ColorPaletteTransform("color-primary--ref--300", "primary", "300"),
  new ColorPaletteTransform("color-primary--ref--400", "primary", "400"),
  new ColorPaletteTransform("color-primary--ref--500", "primary", "500"),
  new ColorPaletteTransform("color-primary--ref--600", "primary", "600"),
  new ColorPaletteTransform("color-primary--ref--700", "primary", "700"),
  new ColorPaletteTransform("color-primary--ref--800", "primary", "800"),
  new ColorPaletteTransform("color-primary--ref--900", "primary", "900"),
  new ColorPaletteTransform("color-primary--ref--A100", "primary", "A100"),
  new ColorPaletteTransform("color-primary--ref--A200", "primary", "A200"),
  new ColorPaletteTransform("color-primary--ref--A400", "primary", "A400"),
  new ColorPaletteTransform("color-primary--ref--A700", "primary", "A700"),

  new ColorPaletteTransform("color-primary--ref--50-contrast", "primary", "50-contrast"),
  new ColorPaletteTransform("color-primary--ref--100-contrast", "primary", "100-contrast"),
  new ColorPaletteTransform("color-primary--ref--200-contrast", "primary", "200-contrast"),
  new ColorPaletteTransform("color-primary--ref--300-contrast", "primary", "300-contrast"),
  new ColorPaletteTransform("color-primary--ref--400-contrast", "primary", "400-contrast"),
  new ColorPaletteTransform("color-primary--ref--500-contrast", "primary", "500-contrast"),
  new ColorPaletteTransform("color-primary--ref--600-contrast", "primary", "600-contrast"),
  new ColorPaletteTransform("color-primary--ref--700-contrast", "primary", "700-contrast"),
  new ColorPaletteTransform("color-primary--ref--800-contrast", "primary", "800-contrast"),
  new ColorPaletteTransform("color-primary--ref--900-contrast", "primary", "900-contrast"),
  new ColorPaletteTransform("color-primary--ref--A100-contrast", "primary", "A100-contrast"),
  new ColorPaletteTransform("color-primary--ref--A200-contrast", "primary", "A200-contrast"),
  new ColorPaletteTransform("color-primary--ref--A400-contrast", "primary", "A400-contrast"),
  new ColorPaletteTransform("color-primary--ref--A700-contrast", "primary", "A700-contrast"),

  new ColorPaletteTransform("color-secondary--ref--50", "secondary", "50"),
  new ColorPaletteTransform("color-secondary--ref--100", "secondary", "100"),
  new ColorPaletteTransform("color-secondary--ref--200", "secondary", "200"),
  new ColorPaletteTransform("color-secondary--ref--300", "secondary", "300"),
  new ColorPaletteTransform("color-secondary--ref--400", "secondary", "400"),
  new ColorPaletteTransform("color-secondary--ref--500", "secondary", "500"),
  new ColorPaletteTransform("color-secondary--ref--600", "secondary", "600"),
  new ColorPaletteTransform("color-secondary--ref--700", "secondary", "700"),
  new ColorPaletteTransform("color-secondary--ref--800", "secondary", "800"),
  new ColorPaletteTransform("color-secondary--ref--900", "secondary", "900"),
  new ColorPaletteTransform("color-secondary--ref--A100", "secondary", "A100"),
  new ColorPaletteTransform("color-secondary--ref--A200", "secondary", "A200"),
  new ColorPaletteTransform("color-secondary--ref--A400", "secondary", "A400"),
  new ColorPaletteTransform("color-secondary--ref--A700", "secondary", "A700"),

  new ColorPaletteTransform("color-secondary--ref--50-contrast", "secondary", "50-contrast"),
  new ColorPaletteTransform("color-secondary--ref--100-contrast", "secondary", "100-contrast"),
  new ColorPaletteTransform("color-secondary--ref--200-contrast", "secondary", "200-contrast"),
  new ColorPaletteTransform("color-secondary--ref--300-contrast", "secondary", "300-contrast"),
  new ColorPaletteTransform("color-secondary--ref--400-contrast", "secondary", "400-contrast"),
  new ColorPaletteTransform("color-secondary--ref--500-contrast", "secondary", "500-contrast"),
  new ColorPaletteTransform("color-secondary--ref--600-contrast", "secondary", "600-contrast"),
  new ColorPaletteTransform("color-secondary--ref--700-contrast", "secondary", "700-contrast"),
  new ColorPaletteTransform("color-secondary--ref--800-contrast", "secondary", "800-contrast"),
  new ColorPaletteTransform("color-secondary--ref--900-contrast", "secondary", "900-contrast"),
  new ColorPaletteTransform("color-secondary--ref--A100-contrast", "secondary", "A100-contrast"),
  new ColorPaletteTransform("color-secondary--ref--A200-contrast", "secondary", "A200-contrast"),
  new ColorPaletteTransform("color-secondary--ref--A400-contrast", "secondary", "A400-contrast"),
  new ColorPaletteTransform("color-secondary--ref--A700-contrast", "secondary", "A700-contrast"),

  new ColorPaletteTransform("color-error--ref--50", "error", "50"),
  new ColorPaletteTransform("color-error--ref--100", "error", "100"),
  new ColorPaletteTransform("color-error--ref--200", "error", "200"),
  new ColorPaletteTransform("color-error--ref--300", "error", "300"),
  new ColorPaletteTransform("color-error--ref--400", "error", "400"),
  new ColorPaletteTransform("color-error--ref--500", "error", "500"),
  new ColorPaletteTransform("color-error--ref--600", "error", "600"),
  new ColorPaletteTransform("color-error--ref--700", "error", "700"),
  new ColorPaletteTransform("color-error--ref--800", "error", "800"),
  new ColorPaletteTransform("color-error--ref--900", "error", "900"),
  new ColorPaletteTransform("color-error--ref--A100", "error", "A100"),
  new ColorPaletteTransform("color-error--ref--A200", "error", "A200"),
  new ColorPaletteTransform("color-error--ref--A400", "error", "A400"),
  new ColorPaletteTransform("color-error--ref--A700", "error", "A700"),

  new ColorPaletteTransform("color-error--ref--50-contrast", "error", "50-contrast"),
  new ColorPaletteTransform("color-error--ref--100-contrast", "error", "100-contrast"),
  new ColorPaletteTransform("color-error--ref--200-contrast", "error", "200-contrast"),
  new ColorPaletteTransform("color-error--ref--300-contrast", "error", "300-contrast"),
  new ColorPaletteTransform("color-error--ref--400-contrast", "error", "400-contrast"),
  new ColorPaletteTransform("color-error--ref--500-contrast", "error", "500-contrast"),
  new ColorPaletteTransform("color-error--ref--600-contrast", "error", "600-contrast"),
  new ColorPaletteTransform("color-error--ref--700-contrast", "error", "700-contrast"),
  new ColorPaletteTransform("color-error--ref--800-contrast", "error", "800-contrast"),
  new ColorPaletteTransform("color-error--ref--900-contrast", "error", "900-contrast"),
  new ColorPaletteTransform("color-error--ref--A100-contrast", "error", "A100-contrast"),
  new ColorPaletteTransform("color-error--ref--A200-contrast", "error", "A200-contrast"),
  new ColorPaletteTransform("color-error--ref--A400-contrast", "error", "A400-contrast"),
  new ColorPaletteTransform("color-error--ref--A700-contrast", "error", "A700-contrast"),

  new VarValueReplaceTransform("--mdc-theme-primary", "color-primary"),
  new VarValueReplaceTransform("--mdc-theme-secondary", "color-secondary"),
  new VarValueReplaceTransform("--mdc-theme-error", "color-error"),
  new VarValueReplaceTransform("--mdc-theme-surface", "color-surface"),
];
